#!/usr/bin/env bash
# auto-generated by buildstrap-deb/generate_config.py from matrix.yml

declare -A ubuntu_codename_to_numeric=(
  [focal]=20.04 [jammy]=22.04 [noble]=24.04
)

declare -A debian_codename_to_numeric=(
  [bookworm]=12 [trixie]=13
)

codename_to_numeric_tag() {
  local dist="$1"
  local codename="$2"
  case "$dist" in
    ubuntu)
      local num="${ubuntu_codename_to_numeric[$codename]}"
      if [[ -n "$num" ]]; then
        if [[ "$num" == *.* ]]; then
          echo -n "ubuntu${num}"
        else
          local yy=${num:0:2}; local mm=${num:2:2}
          echo -n "ubuntu${yy}.${mm}"
        fi
      else
        echo -n "ubuntu$codename"
      fi
      ;;
    debian)
      local num="${debian_codename_to_numeric[$codename]}"
      if [[ -n "$num" ]]; then
        echo -n "debian${num}"
      else
        echo -n "debian$codename"
      fi
      ;;
    *)
      echo -n "${dist}${codename}"
      ;;
  esac
}
